### ISSUE TITLE
升级成从rom包直链直接解包获取boot.img再修补啊

### ISSUE THREAD

**Issue by httpsColon** [xyazzrany/Action_Magisk_PATCHE#1]
用payload-dumper-go项目解包快
payload-dumper-go -p boot payload.bin

**Comment by xyazzrany** [comment]
后面会改的

**Comment by xyazzrany** [comment]
> 使用payload-dumper-go项目解包快 payload-dumper-go -p boot payload.bin

你action错误 参考这个去改下

如果遇到 “403 资源访问受限”，请去 Settings-Actions-General-Workflow permissions,将它调整至 “Read and write permissions”

**Comment by httpsColon** [comment]
> > 使用payload-dumper-go项目解包快 payload-dumper-go -p boot payload.bin
> 
> 你action错误 参考这个去改下
> 
> 如果遇到 “403 资源访问受限”，请去 Settings-Actions-General-Workflow permissions,将它调整至 “Read and write permissions”

我那个失败的actions记录，是因为我boot直链填错了，另外问下你这个是同步了magisk26.1的patch吗，还有这个是你的项目吗https://github.com/jax0ncai/Magisk_patche.git

**Comment by xyazzrany** [comment]
> > > 使用payload-dumper-go项目解包快 payload-dumper-go -p boot payload.bin
> > 
> > 
> > 你action错误 参考这个去改下
> > 如果遇到 “403 资源访问受限”，请去 Settings-Actions-General-Workflow permissions,将它调整至 “Read and write permissions”
> 
> 我那个失败的actions记录，是因为我boot直链填错了，另外问下你这个是同步了magisk26.1的patch吗，还有这个是你的项目吗https://github.com/jax0ncai/Magisk_patche.git
> 
> github.com/jax0ncai不存在

是我的 我之前的名字叫这个 然后现在改了

**Comment by httpsColon** [comment]
> > > > 使用payload-dumper-go项目解包快 payload-dumper-go -p boot payload.bin
> > > 
> > > 
> > > 你action错误 参考这个去改下
> > > 如果遇到 “403 资源访问受限”，请去 Settings-Actions-General-Workflow permissions,将它调整至 “Read and write permissions”
> > 
> > 
> > 我那个失败的actions记录，是因为我boot直链填错了，另外问下你这个是同步了magisk26.1的patch吗，还有这个是你的项目吗https://github.com/jax0ncai/Magisk_patche.git
> > github.com/jax0ncai不存在
> 
> 是我的 我之前的名字叫这个 然后现在改了

Firmware_extractor是比payload-dumper-go兼容性更好是吧，能支持更多的格式？

**Comment by xyazzrany** [comment]
> > > > > 使用payload-dumper-go项目解包快 payload-dumper-go -p boot payload.bin
> > > > 
> > > > 
> > > > 你action错误 参考这个去改下
> > > > 如果遇到 “403 资源访问受限”，请去 Settings-Actions-General-Workflow permissions,将它调整至 “Read and write permissions”
> > > 
> > > 
> > > 我那个失败的actions记录，是因为我boot直链填错了，另外问下你这个是同步了magisk26.1的patch吗，还有这个是你的项目吗https://github.com/jax0ncai/Magisk_patche.git
> > > github.com/jax0ncai不存在
> > 
> > 
> > 是我的 我之前的名字叫这个 然后现在改了
> 
> Firmware_extractor是比payload-dumper-go兼容性更好是吧，能支持更多的格式？
Firmware_extractor可以指定提取镜像 不用像payload-dumper-go提取所有镜像

**Comment by natsumerinchan** [comment]
> > > > > > 使用payload-dumper-go项目解包快 payload-dumper-go -p boot payload.bin
> > > > > 
> > > > > 
> > > > > 你action错误 参考这个去改下
> > > > > 如果遇到 “403 资源访问受限”，请去 Settings-Actions-General-Workflow permissions,将它调整至 “Read and write permissions”
> > > > 
> > > > 
> > > > 我那个失败的actions记录，是因为我boot直链填错了，另外问下你这个是同步了magisk26.1的patch吗，还有这个是你的项目吗https://github.com/jax0ncai/Magisk_patche.git
> > > > github.com/jax0ncai不存在
> > > 
> > > 
> > > 是我的 我之前的名字叫这个 然后现在改了
> > 
> > 
> > Firmware_extractor是比payload-dumper-go兼容性更好是吧，能支持更多的格式？
> > Firmware_extractor可以指定提取镜像 不用像payload-dumper-go提取所有镜像

payload-dumper-go好像也能指定分区 `payload-dumper-go -p boot,vendor_dlkm`

**Comment by xyazzrany** [comment]
> > > > > > > 使用payload-dumper-go项目解包快 payload-dumper-go -p boot payload.bin
> > > > > > 
> > > > > > 
> > > > > > 你action错误 参考这个去改下
> > > > > > 如果遇到 “403 资源访问受限”，请去 Settings-Actions-General-Workflow permissions,将它调整至 “Read and write permissions”
> > > > > 
> > > > > 
> > > > > 我那个失败的actions记录，是因为我boot直链填错了，另外问下你这个是同步了magisk26.1的patch吗，还有这个是你的项目吗https://github.com/jax0ncai/Magisk_patche.git
> > > > > github.com/jax0ncai不存在
> > > > 
> > > > 
> > > > 是我的 我之前的名字叫这个 然后现在改了
> > > 
> > > 
> > > Firmware_extractor是比payload-dumper-go兼容性更好是吧，能支持更多的格式？
> > > Firmware_extractor可以指定提取镜像 不用像payload-dumper-go提取所有镜像
> 
> payload-dumper-go好像也能指定分区 `./payload-dumper-go -p boot,vendor_dlkm`

我才知道 谢谢了
