### ISSUE TITLE
错误1

### ISSUE THREAD

**Issue by yingloveluo** [xyazzrany/Action_Magisk_PATCHE#4]
Error: Process completed with exit code 
请问这是什么原因？

**Comment by yingloveluo** [comment]
> Error: Process completed with exit code 请问这是什么原因？

**Comment by xyazzrany** [comment]
> Error: Process completed with exit code 请问这是什么原因？

没在你fork的看到你运行啊

**Comment by yingloveluo** [comment]
解决了
